# Generated by Django 4.2.2 on 2023-07-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='document',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='driver.documenttype'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='type',
            field=models.CharField(choices=[('company', 'company'), ('shipper', 'shipper'), ('driver', 'driver')]),
        ),
    ]
