# Generated by Django 4.2.2 on 2023-07-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_documenttype_document_documenttype_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.documenttype'),
        ),
    ]
