# Generated by Django 4.2.3 on 2023-07-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyemployee'),
        ('driver', '0004_driver_city_driver_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
