# Generated by Django 4.2.2 on 2023-07-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='max_volume',
        ),
    ]
