# Generated by Django 4.2.3 on 2023-07-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyemployee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyemployee',
            old_name='title',
            new_name='position',
        ),
    ]
