# Generated by Django 4.2.2 on 2023-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('loader', 'Loader'), ('shipper', 'Shipper')], default='shipper', max_length=10),
        ),
    ]
