# Generated by Django 4.2.3 on 2023-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'superuser'), ('shipper', 'shipper'), ('driver', 'driver'), ('company_admin', 'company_admin')], default='shipper', max_length=20),
        ),
    ]
