# Generated by Django 4.2.3 on 2023-07-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_phone_number'),
        ('user', '0010_user_role'),
    ]

    operations = [
    ]
