# Generated by Django 4.2.3 on 2023-07-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_rating_count_rating_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
