# Generated by Django 4.2.2 on 2023-07-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('shipper', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('loading_loc', models.CharField(max_length=123)),
                ('delivery_dest', models.CharField(max_length=123)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordertype')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper')),
            ],
        ),
    ]
