# Generated by Django 4.2.2 on 2023-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
