# Generated by Django 4.2.2 on 2023-07-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_volume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderType',
            new_name='CargoType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='cargo_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='volume',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('quick', 'qucik'), ('slow', 'slow')], default='slow'),
        ),
    ]
