# Generated by Django 4.2.3 on 2023-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('quick', 'quick'), ('slow', 'slow')]),
        ),
    ]
