# Generated by Django 4.2.3 on 2023-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdriver',
            name='driver_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
