# Generated by Django 4.2.3 on 2023-07-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_city_driver_is_available'),
        ('order', '0009_alter_orderdriver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdriver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
