# Generated by Django 4.2.3 on 2023-07-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderoffer_delete_orderdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoffer',
            name='rpm',
            field=models.IntegerField(default=5),
        ),
    ]
