# Generated by Django 4.2.3 on 2023-07-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_orderoffer_rpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoffer',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
