# Generated by Django 4.2.3 on 2023-07-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyemployee'),
        ('driver', '0005_driver_company'),
        ('order', '0015_alter_orderoffer_rpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoffer',
            name='companyemployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyemployee'),
        ),
        migrations.AlterField(
            model_name='orderoffer',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
