# Generated by Django 4.2.3 on 2023-07-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyemployee'),
        ('order', '0018_rename_companyemployee_orderoffer_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderoffer',
            old_name='company',
            new_name='companyemployee',
        ),
        migrations.AddField(
            model_name='order',
            name='companyemployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyemployee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
