# Generated by Django 4.2.3 on 2023-07-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_rename_company_orderoffer_companyemployee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='companyemployee',
        ),
    ]
