# Generated by Django 4.2.3 on 2023-07-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_delivery_type'),
        ('order', '0020_remove_order_companyemployee'),
    ]

    operations = [
    ]
