# Generated by Django 4.2.3 on 2023-07-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_merge_20230706_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('quick', 'quick'), ('slow', 'slow')], default='slow'),
        ),
    ]
