# Generated by Django 4.2.3 on 2023-07-07 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0022_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
